name: Sync Profile README

on:
  push:
    paths:
      - README.md
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio
        uses: actions/checkout@v4

      - name: Prepare README
        run: |
          cp README.md profile_README.md

      - name: Push to profile repo
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source_file: 'profile_README.md'
          destination_repo: 'Rushikesh-S-Ware/Rushikesh-S-Ware'
          destination_folder: ''
          destination_branch: 'main'
          user_email: 'your-email@example.com'
          user_name: 'rushikesh-s-ware'
          commit_message: 'Sync profile README from portfolio'
          overwrite: true
          file_name: 'README.md'
